"""audit event scope

Revision ID: 733e83487122
Revises: 93e99d63787f
Create Date: 2026-09-02 16:39:51.890922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733e83487122'
down_revision: Union[str, Sequence[str], None] = '93e99d63787f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('project_path', sa.String(), nullable=True))
        batch_op.create_index('ix_audit_events_project', ['base_url', 'project_path'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_project')
        batch_op.drop_column('project_path')
        batch_op.drop_column('base_url')

    # ### end Alembic commands ###
